/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tac_assembly_generator.ui;

import tac_assembly_generator.files.FileManager;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import tac_assembly_generator.optimized.HtmlCreator;

/**
 *
 * @author sergio
 */
public class MainFrame extends javax.swing.JFrame {

    public final static ImageIcon BG = new ImageIcon("src/main/java/tac_assembly_generator/ui/images/bg1.jpg");
    private FileManager fileManager;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        fileManager = new FileManager();
        FileMlg.uiManage();
        initComponents();
        setBackground();
        fileManager.loadExampleMLG(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        tabs = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        generateMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        runMenu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        stackMenu = new javax.swing.JMenuItem();
        menuOp = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        tabs.setBackground(new java.awt.Color(0, 0, 0));
        tabs.setForeground(new java.awt.Color(255, 255, 255));
        tabs.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabs.setOpaque(true);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        saveMenuItem.setText("Save");
        saveMenuItem.setEnabled(false);
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        saveAsMenuItem.setText("Save As...");
        saveAsMenuItem.setEnabled(false);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveAsMenuItem);

        exitMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        generateMenu.setBackground(new java.awt.Color(51, 51, 51));
        generateMenu.setForeground(new java.awt.Color(255, 255, 255));
        generateMenu.setText("Generate Code");
        generateMenu.setEnabled(false);
        generateMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem6.setText("3AC");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        generateMenu.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem7.setText("Optimization");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        generateMenu.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem8.setText("Assembly");
        generateMenu.add(jMenuItem8);

        jMenuBar1.add(generateMenu);

        runMenu.setBackground(new java.awt.Color(51, 51, 51));
        runMenu.setForeground(new java.awt.Color(255, 255, 255));
        runMenu.setText("Run");
        runMenu.setEnabled(false);
        runMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem9.setText("3AC");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        runMenu.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem10.setText("Optimization");
        runMenu.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem11.setText("Assembly");
        runMenu.add(jMenuItem11);

        jMenuBar1.add(runMenu);

        reportMenu.setForeground(new java.awt.Color(255, 255, 255));
        reportMenu.setText("Reports");
        reportMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        stackMenu.setText("StackTAC");
        stackMenu.setEnabled(false);
        stackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackMenuActionPerformed(evt);
            }
        });
        reportMenu.add(stackMenu);

        menuOp.setText("Optimization");
        menuOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpActionPerformed(evt);
            }
        });
        reportMenu.add(menuOp);

        jMenuBar1.add(reportMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        NameChooser nc = new NameChooser(this, true);
        nc.setVisible(true);
        FileMlg newFile = nc.getFileMlg();
        if (newFile != null) {
            addFileMlg(newFile);
        }
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        fileManager.openFile(this);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        if (!fileManager.getFiles().isEmpty()) {
            fileManager.saveFile(tabs.getSelectedIndex(), this);
        }

    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        if (!fileManager.getFiles().isEmpty()) {
            fileManager.saveAsFile(tabs.getSelectedIndex(), this);
        }
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        fileManager.cleanTextPanes(tabs.getSelectedIndex());
        fileManager.getFiles().get(tabs.getSelectedIndex()).getLanguageManager().generateTAC(this);
        stackMenu.setEnabled(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void stackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackMenuActionPerformed
        StackTable stackTable= new StackTable(fileManager.getFiles().get(tabs.getSelectedIndex()).getLanguageManager().getStack());
        stackTable.setVisible(true);
    }//GEN-LAST:event_stackMenuActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
        fileManager.getFiles().get(tabs.getSelectedIndex()).getLanguageManager().generateExitutable(this);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        fileManager.cleanTextPanes(tabs.getSelectedIndex());
        fileManager.getFiles().get(tabs.getSelectedIndex()).getLanguageManager().generateOptimized(this);
        stackMenu.setEnabled(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpActionPerformed
        HtmlCreator hc= new HtmlCreator();
        hc.createHtml(null, null, null);
    }//GEN-LAST:event_menuOpActionPerformed
    public void addFileMlg(FileMlg newFile) {
        fileManager.addFileMlg(newFile);
        tabs.add(newFile.getName(), newFile);
        tabs.setSelectedIndex(tabs.getTabCount() - 1);
        if (fileManager.getFiles().isEmpty()) {
            enableMenus(false);
        } else {
            enableMenus(true);
        }
    }

    public void enableMenus(boolean en) {
        saveAsMenuItem.setEnabled(en);
        saveMenuItem.setEnabled(en);
        generateMenu.setEnabled(en);
        runMenu.setEnabled(en);
        reportMenu.setEnabled(en);

    }

    public void enableOptimizedHtml(){
        menuOp.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    private void setBackground() {
        System.out.println(BG.getImage());
        JLabel backgroundLbl = new JLabel();
        backgroundLbl.setSize(1920, 1200);
        backgroundLbl.setLocation(0, 0);
        backgroundLbl.setIcon(BG);
        this.add(backgroundLbl);
        backgroundLbl.setVisible(true);

    }

 

    public JTextPane getOutputPannel() {
        return fileManager.getOutputPane(tabs.getSelectedIndex());
    }

    public JTextPane getTACPannel() {
        return fileManager.getTACPane(tabs.getSelectedIndex());
    }

    public JTextPane getOptimizedPannel() {
        return fileManager.getOptimizedPane(tabs.getSelectedIndex());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu generateMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuOp;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenu runMenu;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem stackMenu;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
