
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 12 21:36:37 CST 2020
//----------------------------------------------------

package tac_assembly_generator.languages.analyzers.syntax;

/** CUP generated class containing symbol constants. */
public class SimbolosMlg {
  /* terminals */
  public static final int LEFT_CB = 75;
  public static final int SYSTEM_OUT_PRINT = 69;
  public static final int DIVISION = 10;
  public static final int THEN_VB = 61;
  public static final int LESS_THAN = 36;
  public static final int WRITE_VB = 53;
  public static final int PARENTHESIS_B = 6;
  public static final int PARENTHESIS_A = 5;
  public static final int GREATER_THAN = 33;
  public static final int CONST = 86;
  public static final int CASE_VB = 63;
  public static final int STEP_VB = 56;
  public static final int NEXT_VB = 57;
  public static final int INDENT = 81;
  public static final int LESS_THAN_EQUAL = 38;
  public static final int COMMA = 15;
  public static final int DEDENT = 80;
  public static final int ELSE_IF_VB = 60;
  public static final int ELIF = 85;
  public static final int FLOAT_TYPE = 17;
  public static final int RETURN_VB = 51;
  public static final int JAVA_SEPERATOR = 45;
  public static final int DEFAULT_J = 72;
  public static final int MULTIPLICATION = 9;
  public static final int FALSE = 30;
  public static final int NOT = 21;
  public static final int DEF = 82;
  public static final int CHAR_TYPE = 18;
  public static final int ERROR = 3;
  public static final int SUB_VB = 50;
  public static final int MOD = 11;
  public static final int AMPERSON = 14;
  public static final int INCLUDE = 89;
  public static final int GREATER_THAN_EQUAL = 37;
  public static final int NUMBER = 43;
  public static final int CLRSCR = 91;
  public static final int SWITCH_J = 70;
  public static final int CLASS_J = 65;
  public static final int PRINTF = 90;
  public static final int TRUE = 29;
  public static final int CASE_J = 71;
  public static final int VOID_J = 66;
  public static final int PLUS = 7;
  public static final int WHILE = 27;
  public static final int EQUAL = 4;
  public static final int SYSTEM_OUT_PRINTLN = 68;
  public static final int EQUAL_BOOL = 39;
  public static final int DECIMAL = 44;
  public static final int CHAR = 42;
  public static final int GETCH = 92;
  public static final int CONSOLE_VB = 52;
  public static final int DO = 28;
  public static final int FOR = 26;
  public static final int PUBLIC = 25;
  public static final int RETURN = 34;
  public static final int ELSE = 32;
  public static final int FLOATINPUT = 24;
  public static final int BREAK = 73;
  public static final int POINT = 13;
  public static final int SELECT_VB = 62;
  public static final int END_VB = 49;
  public static final int AS_VB = 47;
  public static final int SEMICOLON = 74;
  public static final int EOF = 0;
  public static final int LEFT_BRACKET = 87;
  public static final int DIM_VB = 46;
  public static final int FUNCTION_VB = 48;
  public static final int PRINT = 35;
  public static final int PROGRAM_SEPERATOR = 79;
  public static final int CHARINPUT = 23;
  public static final int LOOP_VB = 59;
  public static final int MAIN = 94;
  public static final int MINUS = 8;
  public static final int IN = 83;
  public static final int OR = 19;
  public static final int error = 1;
  public static final int SCAN_F = 93;
  public static final int RIGHT_BRACKET = 88;
  public static final int RIGHT_CB = 76;
  public static final int WRITELN_VB = 54;
  public static final int IF = 31;
  public static final int ID = 41;
  public static final int DIFERENT_VB = 58;
  public static final int INTEGER_TYPE = 16;
  public static final int INTINPUT = 22;
  public static final int COLON = 77;
  public static final int VB_SEPERATOR = 2;
  public static final int RANGE = 84;
  public static final int STRING = 40;
  public static final int RETURN_J = 67;
  public static final int AND = 20;
  public static final int LINE_BREAK = 12;
  public static final int TO_VB = 55;
  public static final int DIFERENT_J = 78;
  public static final int PYTHON_SEPERATOR = 64;
}

