
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 08 11:40:38 CST 2020
//----------------------------------------------------

package tac_assembly_generator.languages.analyzers.syntax;

/** CUP generated class containing symbol constants. */
public class SimbolosMlg {
  /* terminals */
  public static final int LEFT_CB = 75;
  public static final int SYSTEM_OUT_PRINT = 70;
  public static final int DIVISION = 10;
  public static final int THEN_VB = 63;
  public static final int LESS_THAN = 38;
  public static final int WRITE_VB = 53;
  public static final int PARENTHESIS_B = 6;
  public static final int PARENTHESIS_A = 5;
  public static final int GREATER_THAN = 32;
  public static final int CONST = 85;
  public static final int CASE_VB = 65;
  public static final int STEP_VB = 56;
  public static final int NEXT_VB = 57;
  public static final int INDENT = 80;
  public static final int LESS_THAN_EQUAL = 40;
  public static final int COMMA = 14;
  public static final int DEDENT = 79;
  public static final int ELSE_IF_VB = 62;
  public static final int ELIF = 84;
  public static final int FLOAT_TYPE = 16;
  public static final int JAVA_SEPERATOR = 46;
  public static final int MULTIPLICATION = 9;
  public static final int FALSE = 29;
  public static final int NOT = 20;
  public static final int DEF = 81;
  public static final int CHAR_TYPE = 17;
  public static final int ERROR = 3;
  public static final int SUB_VB = 51;
  public static final int MOD = 11;
  public static final int AMPERSON = 13;
  public static final int INCLUDE = 88;
  public static final int GREATER_THAN_EQUAL = 39;
  public static final int BY_VAL = 58;
  public static final int NUMBER = 44;
  public static final int CLRSCR = 90;
  public static final int SWITCH_J = 71;
  public static final int CLASS_J = 67;
  public static final int PRINTF = 89;
  public static final int TRUE = 28;
  public static final int VOID_J = 68;
  public static final int PLUS = 7;
  public static final int WHILE = 26;
  public static final int EQUAL = 4;
  public static final int SYSTEM_OUT_PRINTLN = 69;
  public static final int DECIMAL = 45;
  public static final int CHAR = 43;
  public static final int GETCH = 91;
  public static final int CONSOLE_VB = 52;
  public static final int SWITCH = 35;
  public static final int DO = 27;
  public static final int FOR = 25;
  public static final int PUBLIC = 24;
  public static final int RETURN = 33;
  public static final int ELSE = 31;
  public static final int FLOATINPUT = 23;
  public static final int BREAK = 72;
  public static final int POINT = 12;
  public static final int SELECT_VB = 64;
  public static final int END_VB = 50;
  public static final int AS_VB = 48;
  public static final int SEMICOLON = 73;
  public static final int EOF = 0;
  public static final int LEFT_BRACKET = 86;
  public static final int DIM_VB = 47;
  public static final int FUNCTION_VB = 49;
  public static final int THIS = 74;
  public static final int DEFAULT = 36;
  public static final int PRINT = 34;
  public static final int PROGRAM_SEPERATOR = 78;
  public static final int CHARINPUT = 22;
  public static final int LOOP_VB = 60;
  public static final int MAIN = 93;
  public static final int MINUS = 8;
  public static final int IN = 82;
  public static final int OR = 18;
  public static final int error = 1;
  public static final int SCAN_F = 92;
  public static final int RIGHT_BRACKET = 87;
  public static final int RIGHT_CB = 76;
  public static final int WRITELN_VB = 54;
  public static final int IF = 30;
  public static final int ID = 42;
  public static final int DIFERENT_VB = 59;
  public static final int INTEGER_TYPE = 15;
  public static final int INTINPUT = 21;
  public static final int COLON = 77;
  public static final int VB_SEPERATOR = 2;
  public static final int CASE = 37;
  public static final int NEW = 61;
  public static final int RANGE = 83;
  public static final int STRING = 41;
  public static final int AND = 19;
  public static final int TO_VB = 55;
  public static final int PYTHON_SEPERATOR = 66;
}

